### ISSUE TITLE
Cannot run 'ionic cordova run android'

### ISSUE THREAD

**Issue by iazureenaa** [iazureenaa/CollinDiary2021#1]
1. Trying to run 'ionic serve --livereload-url' but got this error below.
![image](https://user-images.githubusercontent.com/46596248/144812043-436a9e82-392e-41b7-b096-11fea019cff3.png)

2. Found solution here: https://stackoverflow.com/questions/55402497/how-to-fix-typeerror-cannot-read-property-then-of-undefined-typeerror-canno

3. Understood the error  - ionic serve wont work to run in browser without cordova
![image](https://user-images.githubusercontent.com/46596248/144812261-dd1d63b4-d503-44f5-ae21-e2dcbab525a8.png)

4. Which lead to warning in picture - SQLite needs cordova to run as browser
![image](https://user-images.githubusercontent.com/46596248/144811709-9115b165-2f98-41c2-931d-43a481d36193.png)

5. Cordova has been installed
![image](https://user-images.githubusercontent.com/46596248/144812702-da7aba44-e8be-460d-a3ca-65ebf07bab63.png)

6. Android SDK Setup already tried, updated the android sdk, setup environmental variables + path, restart also not working.

**Comment by shakucing** [comment]
which means, next solution is to start adding ionic platform android. as plugin that has dependency with os specific, ionic serve is to be avoided moving forward

**Comment by shakucing** [comment]
there are 2 tehcniques, 

using cordova

https://ionicframework.com/docs/cli/commands/cordova-platform

and another is using capacitor

https://ionicframework.com/docs/cli/commands/capacitor-add

cordova vs capacitor

https://ionic.io/resources/articles/capacitor-vs-cordova-modern-hybrid-app-development

**Comment by iazureenaa** [comment]
> which means, next solution is to start adding ionic platform android. as plugin that has dependency with os specific, ionic serve is to be avoided moving forward

Understood as - dont use ionic serve as it has dependency with specific os, instead use ionic platform android. Am I right?

**Comment by iazureenaa** [comment]
> there are 2 tehcniques,
> 
> using cordova
> 
> https://ionicframework.com/docs/cli/commands/cordova-platform
> 
> and another is using capacitor
> 
> https://ionicframework.com/docs/cli/commands/capacitor-add
> 
> cordova vs capacitor
> 
> https://ionic.io/resources/articles/capacitor-vs-cordova-modern-hybrid-app-development


Understood - cordova/capacitor are used to run web app/browser in devices (ios, android etc) which makes the same code can be run in any platform (PWA). 

![image](https://user-images.githubusercontent.com/46596248/144815278-0d5f9e6f-43ac-404c-9e41-108b6c606365.png)
![image](https://user-images.githubusercontent.com/46596248/144815363-6f6eefd7-1f01-4efc-b69f-80ef150d417d.png)

Failed to run 'ionic capacitor add android'

**Comment by shakucing** [comment]
if already installed cordova, then capacitor installation flow is not required

can i have the log file after running "ionic cordova run android"?

**Comment by iazureenaa** [comment]
> if already installed cordova, then capacitor installation flow is not required
> 
> can i have the log file after running "ionic cordova run android"?
[log.txt](https://github.com/iazureenaa/CollinDiary2021/files/7664988/log.txt)

[ionic cordova build android log.txt](https://github.com/iazureenaa/CollinDiary2021/files/7665026/ionic.cordova.build.android.log.txt)

**Comment by shakucing** [comment]
this is possible due to pre-requisite path issue is in different directory.

for old collin diary, previously where does the folder located at? D drive?
try to attempt to copy paste and put in same parent directory as old collin diary and run again.

otherwise we have to do call session to do screen share

**Comment by iazureenaa** [comment]
> this is possible due to pre-requisite path issue is in different directory.
> 
> for old collin diary, previously where does the folder located at? D drive? try to attempt to copy paste and put in same parent directory as old collin diary and run again.
> 
> otherwise we have to do call session to do screen share

CollinDiary2021 moved to old parent folder but still have the same error

![image](https://user-images.githubusercontent.com/46596248/144961179-548fd298-6c95-48a8-8ba9-621848d1a697.png)

![image](https://user-images.githubusercontent.com/46596248/144961247-157b424c-e045-4443-a0cf-917636ec97a9.png)

FYI, the environmental variables and path;

![image](https://user-images.githubusercontent.com/46596248/144961357-ddcd5667-46af-4a21-bc08-dc71b74bd22b.png)

![image](https://user-images.githubusercontent.com/46596248/144961402-876d651c-e855-4af2-bd94-c06b6d89d978.png)

![image](https://user-images.githubusercontent.com/46596248/144961443-ac01116c-3c34-4785-89ce-1d865e17fec9.png)

**Comment by shakucing** [comment]
definitely need to investigate closely from my end

lets call at 1.30pm

**Comment by iazureenaa** [comment]
Solved, related to gradle issue. Used cmd terminal instead.
