### ISSUE TITLE
Failed to install ngx-translate

### ISSUE THREAD

**Issue by iazureenaa** [iazureenaa/CollinDiary2021#2]
References: 

1. https://enappd.com/blog/how-to-translate-in-ionic-internationalization-and-localization/143/
2. https://www.positronx.io/angular-internationalization-i18n-with-ngx-translate-tutorial/
3. https://www.npmjs.com/package/@ngx-translate/core

Tried to install ngx-translate  but got this error

![image](https://user-images.githubusercontent.com/46596248/145145826-44378b53-f4ab-4140-919b-5bd45f2eaaa8.png)

Trying to search for compatible version of ngx-translate  for angular 12, but only got this 

![Uploading image.png…]()

**Comment by shakucing** [comment]
after lunch break will try locally using following concept:
https://www.angularfix.com/2021/09/unable-to-resolve-dependency-tree-error.html?m=1

**Comment by shakucing** [comment]
my env info:

Ionic:

   Ionic CLI                     : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.9.1
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.2.13
   @angular/cli                  : 12.2.13
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.18.0 (/usr/local/bin/node)
   npm    : 6.14.15
   OS     : macOS Big Sur

**Comment by iazureenaa** [comment]
Solved by downgrading versions of npm, cli & angular.
